services:
  register-service:
    build: ./backend/serviceUser
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: senai
      DB_PASSWORD: senai
      DB_NAME: Panteao-Pizzaria
      
  pizza-service:
    build: ./backend/servicePizza
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: senai
      DB_PASSWORD: senai
      DB_NAME: Panteao-Pizzaria

  login-service:
    build: ./backend/serviceLogin
    ports:
      - "3003:3003"
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: senai
      DB_PASSWORD: senai
      DB_NAME: Panteao-Pizzaria

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: senai
      POSTGRES_PASSWORD: senai
      POSTGRES_DB: Panteao-Pizzaria
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
      
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always

volumes:
  pgdata: